name: 'Code quality checks'

on:
  workflow_call:

jobs:
  psalm-codeql:
    name: 'Checking Psalm CodeQL'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          tools: composer
      - run: |
          make ci
          composer validate --strict
          composer install --no-interaction --no-progress
      - continue-on-error: true
        run: vendor/bin/psalm --output-format=github --report=/tmp/psalm/report.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: /tmp/psalm/report.sarif
  psalm-security:
    name: 'Checking Psalm Security'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          tools: composer
      - run: |
          make ci
          composer validate --strict
          composer install --no-interaction --no-progress
      - continue-on-error: true
        run: vendor/bin/psalm --taint-analysis --output-format=github --report=/tmp/psalm/report.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: /tmp/psalm/report.sarif
